apiVersion: apps/v1
kind: Deployment
metadata:
  name: habit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: habit-frontend
  template:
    metadata:
      labels:
        app: habit-frontend
    spec:
      containers:
      - name: frontend
        image: hab-frontend
        

        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: habit-frontend
spec:
  type: NodePort
  selector:
    app: habit-frontend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30007